version: "2"

formatters:
  enable:
    - gofmt

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
  settings:
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: error-return
        - name: error-strings
        - name: if-return
        - name: range
        - name: indent-error-flow
        - name: superfluous-else
  exclusions:
    generated: strict
